### ISSUE TITLE
Test how we can get the app if it is initialized outside of firebase

### ISSUE THREAD

**Issue by mrozbarry** [pairshaped/elm-firebase#23]
**Note:** Taken from a [discussion with @ucode](https://elmlang.slack.com/archives/C47CE4KM1/p1491578494623855) on slack#elm-firebase

The main concern is being able to access the app when using some [newer environment configuration options](https://firebase.googleblog.com/2017/04/easier-configuration-for-firebase-on-web.html), where app is initialized outside of elm.

Here are my initial thoughts (re-structured), from most to least preferable

1. Use `Firebase.apps`
  - It has already been implemented, and *should* be available regardless of configuration, but I haven't verified this yet.
  - Could be wrapped in a convenience methods:
    - `Firebase.getAppByName : String -> Maybe App`
    - `Firebase.getDefaultApp : Maybe App`
  - Doesn't break any previous code using elm-firebase
2. Change `Firebase.init : Config -> App` to `Firebase.init : Maybe Config -> Maybe App`
  - Definitely breaks old code
  - Forces developers to check to see if their app is valid
    - This may actually be the right thing to do, as credentials could be invalid, and there's no current way to know other than a js error.
  - May be a good opportunity to implement `Config.project_id`, which is a new optional param.

This spawns another important issue, how does a developer know their app is actually valid? I'd rather have some sort of check in-code rather than have everything compile, but immediate runtime error after initializing a bad app. Using the easier configuration suggested by the firebase blog post should mostly eliminate bad configs, but it's probably still possible (get everything configured, but then delete the project on the firebase console).

My initial inclination is to point towards option 1., but after thinking about Firebase.App validity, 2. actually starts to look much better. I even have a similar pattern in some of the Reference and Query methods that take optional javascript params.

**Comment by samueller** [comment]
I like the 2nd option, though rather than have `Firebase.init` take 2 different kinds of input (nothing or a `Config`, encapsulated in a `Maybe Config`), what about having 2 separate init functions? `Firebase.init : Config -> Maybe App` (keep the original) and `Firebase.initDefault : Maybe App`?

**Comment by mrozbarry** [comment]
So I think there are two necessary functions:

 1. `Firebase.findAppByName : String -> Maybe App`.  Find an app by it's name. Can be implemented directly in Elm. Won't always do the right thing (Nothing stopping firebase from changing the default app name from `"[DEFAULT]"`). This is more useful in a situation where there are multiple firebase apps.
 2. `Firebase.currentApp : Maybe App`. Get the app from `window.firebase.app`. Must be coded from native, but will probably do the right thing.

I think I can get this working tonight, and a demo out for both of these in the next few days.

**Comment by samueller** [comment]
I saw your slack message regarding avoiding multiple `init` functions since the app has already been initialized. If there's no initialization going on, then I wouldn't name a function with `init`. I was thinking the `init` functions would at least check that there is, in fact, a valid Firebase app. That's a form of initialization, at least in the Elm side.

Otherwise, I like `Firebase.currentApp` or `Firebase.defaultApp`. What about just `Firebase.app`? `current` feels like it might change and `default` feels like there's a global default app everyone shares.

Regarding `Firebase.findAppByName`, I personally like nouns for function names if they're not performing actions (or returning a `Cmd` or `Task`). I don't know what the coding conventions are for this project.. my preference would be `Firebase.appFromName` or `Firebase.appByName`.

**Comment by mrozbarry** [comment]
@samueller If you already have a project using the new environment initialization, want to test spin with `"ref": "initialized-outside-elm"` in your elm-packages. I did some basic tests and it seems to be good so far.

**Comment by samueller** [comment]
I can confirm that your code works perfectly for me. Both using `firebase serve` locally and on the web after a `firebase deploy`.
