### ISSUE TITLE
Should we include DataSnapshot hasChild, hasChildren, and numChildren?

### ISSUE THREAD

**Issue by mrozbarry** [pairshaped/elm-firebase#6]
When getting a snapshot from your database, there are functions to see if a child exists, if there are any children, and the number of children. These appear to be wrappers around the child method.

So, are these helper methods actually necessary?  For one, the elm decoder expects a data structure, so for the most part, you will usually know the number of children. For arrays, you would decode into `Dict`, and be able to get the number of keys. You could also use:

```
Firebase.Database.dataSnapshotChild "some/path" snapshot
  |> Firebase.Database.dataSnapshotExists
```

to know if a child path exists.

I'm willing to be wrong, but with many other alternatives, and needing a known json data structure, I can't see a good reason for these to exist.

Thoughts/opinions/rants welcome.

**Comment by tilmans** [comment]
Agree, the slimmer the API the better and this does seem redundant.

**Comment by mrozbarry** [comment]
After thinking it through, I think we'll still include this as part of the library. I do still think it's redundant, but it is a feature of the library, and keeping the function mapping close is important.
